### ISSUE TITLE
使用deep都改不了里面的样式，我想隐藏“calendar-header”

### ISSUE THREAD

**Issue by sparGuan** [xwpongithub/vue-better-calendar#7]
使用deep都改不了里面的样式，我想隐藏“calendar-header”

**Comment by sparGuan** [comment]
![n ban_6 49 g58brgk65v 7](https://user-images.githubusercontent.com/28480563/39348081-331506a0-4a28-11e8-973a-bd45d13dd66b.png)

**Comment by xwpongithub** [comment]
从图中无法得知你是如何做的，你说的deep我不知道是什么意思，但是直接为组件添加一个class，如：
.vue-better-calendar .calendar-header {display:none;}
就可以隐藏header了。

**Comment by xwpongithub** [comment]
新增了hideHeader和hideWeeks两个参数，直接设为true就可以隐藏了
